# Generated by Django 5.0.4 on 2024-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
