# Generated by Django 5.0.6 on 2024-06-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_order_product_alter_order_postal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
    ]
