# Generated by Django 5.0.6 on 2024-06-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Add products'},
        ),
    ]
