# Generated by Django 5.0.6 on 2024-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Add products'},
        ),
    ]
